### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by xpLF1314** [Chasel-Tsui/mmrotate-dcfl#25]
Every time I train for 4 epochs, I report an error. Does anyone know why? thank you!
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu )
![image](https://github.com/user-attachments/assets/e2adf10a-7d89-4a65-9dae-b1f83053f932)

**Comment by Chasel-Tsui** [comment]
This error raises since inds and a apecific variable (bboxes, scores, labels) are not in the same gpu, you can try to manually set them to the same device using .to(device)
